#!/bin/sh
# Remember to change $USER

export USER="nullenvk"
export HOME="/home/$USER"

groups="$(id -Gn "$USER" | tr ' ' ':')"
svdir="$HOME/.runit/service"

exec chpst -u "$USER:$groups" runsvdir "$svdir"
